### ISSUE TITLE
npm  build fails with TypeError: name.replace is not a function

### ISSUE THREAD

**Issue by MansurAshraf** [lamualfa/setup-routify-ts#5]
After create a new project and running `npm run build` results in this error

```
MansurseMacbook :: /tmp/my-routify-app » npm run build

> svelte-app@1.0.0 build
> run-s build:*


> svelte-app@1.0.0 build:app
> routify -b && rollup -c

[Routify] Generated routes in 1 ms

src/main.ts → dist/build...
(!) Plugin typescript: @rollup/plugin-typescript: Typescript 'sourceMap' compiler option must be set to generate source maps.
[!] TypeError: name.replace is not a function

TypeError: name.replace is not a function
    at sanitizeFileName (/private/tmp/my-routify-app/node_modules/rollup/dist/shared/rollup.js:65:17)
    at isPlainPathFragment (/private/tmp/my-routify-app/node_modules/rollup/dist/shared/rollup.js:81:9)
    at renderNamePattern (/private/tmp/my-routify-app/node_modules/rollup/dist/shared/rollup.js:10897:10)
    at Chunk$1.generateId (/private/tmp/my-routify-app/node_modules/rollup/dist/shared/rollup.js:11145:27)
    at Bundle$1.assignChunkIds (/private/tmp/my-routify-app/node_modules/rollup/dist/shared/rollup.js:12424:34)
    at Bundle$1.addFinalizedChunksToBundle (/private/tmp/my-routify-app/node_modules/rollup/dist/shared/rollup.js:12384:14)
    at Bundle$1.generate (/private/tmp/my-routify-app/node_modules/rollup/dist/shared/rollup.js:12368:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at handleGenerateWrite (/private/tmp/my-routify-app/node_modules/rollup/dist/shared/rollup.js:19946:23)

npm ERR! code 1
npm ERR! path /private/tmp/my-routify-app
npm ERR! command failed
npm ERR! command sh -c routify -b && rollup -c

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mansurashraf/.npm/_logs/2020-11-22T04_14_16_174Z-debug.log
ERROR: "build:app" exited with 1.
npm ERR! code 1
npm ERR! path /private/tmp/my-routify-app
npm ERR! command failed
npm ERR! command sh -c run-s build:*

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mansurashraf/.npm/_logs/2020-11-22T04_14_16_213Z-debug.log
```

**Comment by KetaSwe** [comment]
Same as https://github.com/roxiness/routify-starter/issues/78

**Comment by lamualfa** [comment]
@MansurAshraf This bug is caused by the Routify Starter Template, not from `routify-ts`. For the solution please see the following comments: https://github.com/roxiness/routify-starter/issues/78#issuecomment-732138759.
